version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: lawviksh_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sahil@123
      MYSQL_DATABASE: lawviksh_db
      MYSQL_USER: lawviksh_user
      MYSQL_PASSWORD: lawviksh_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./lawdata.sql:/docker-entrypoint-initdb.d/lawdata.sql
    ports:
      - "3306:3306"
    networks:
      - lawviksh_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lawviksh_app
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=lawviksh_db
      - DB_USER=root
      - DB_PASSWORD=Sahil@123
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - API_BASE_URL=https://www.lawvriksh.com/api
      - API_PREFIX=/api
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:3001","http://localhost:5173","http://localhost:8080","http://127.0.0.1:3000","http://127.0.0.1:3001","http://127.0.0.1:5173","http://127.0.0.1:8080","https://www.beta.lawvriksh.com","https://beta.lawvriksh.com","http://www.beta.lawvriksh.com","http://beta.lawvriksh.com","https://app.beta.lawvriksh.com","https://admin.beta.lawvriksh.com"]
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_ALLOW_METHODS=["GET","POST","PUT","DELETE","OPTIONS","PATCH"]
      - CORS_ALLOW_HEADERS=["*"]
      - CORS_EXPOSE_HEADERS=["Content-Length","Content-Type","Authorization"]
      - CORS_MAX_AGE=86400
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lawviksh_network
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: lawviksh_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - lawviksh_network
    profiles:
      - production

volumes:
  mysql_data:
    driver: local
  app_logs:
    driver: local
  app_uploads:
    driver: local

networks:
  lawviksh_network:
    driver: bridge 
